version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./requirements.txt:/app/requirements.txt
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  qdrant:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:6333/readyz"]
      interval: 30s
      timeout: 10s
      retries: 3

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./frontend:/app/frontend
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      app:
        condition: service_healthy
    command: >
      sh -c "cd /app && streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0"
    restart: unless-stopped

volumes:
  qdrant_data:
